site_name: MoeIX | Moe Internet Exchanges

theme: 
  name: material
  language: zh
  highlightjs: true

extra_css:
  - css/hidefooter.css

#repo_url: https://github.com/MoeQing-Network/MoeIX-Homepage

nav:
  - Home: index.md
  - Members: members.md
  - Looking Glass: lg.md